apiVersion: ENC[AES256_GCM,data:ELY=,iv:JdL9BjssT9aUmQ20RPybXs1pYjSqePQ8D68JHr7+C5o=,tag:/jY5lHeeCk5hqARr0m7F6g==,type:str]
kind: ENC[AES256_GCM,data:5qQXn3nD,iv:ow1cYBswft8iSDyVsd/FT3m9pOLh9fWz3g6GtufHiSY=,tag:TEc018PMUamCA7jMN0jzCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:irfZBov9RCd46Ew/yVbMBukqmsmU,iv:tENhFE0/Fu6XzCKjQEEnHlltGRKcjARlnrXvYLN5JIg=,tag:bfrVg7upmEeY+vElaepIEQ==,type:str]
    namespace: ENC[AES256_GCM,data:bnXgacVk8xA=,iv:mCLoUHAs4ze7IHrZodfcVJL4Eg9B7s7qypWhGbGIbvE=,tag:LpZKd+wb55AmPlnos3DZqA==,type:str]
type: ENC[AES256_GCM,data:J/wPlCme,iv:2A7rHdr/udjLEFvmMrrPGUzUxm3FL1tBKmiMPKc3sbA=,tag:wZDWVwhn3dPgrDUQ5Nj3zQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:6z74iW/RhYnP/rQtUP0EBzMAKpMWCAla,iv:AGRLlcXXRZSyMvG1/tN24Ne6xOex7q6ts6njcmbXWDI=,tag:5YLFDOo2f4+OuRLXAOh4rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNnkyVDdvL1FwZHNpUTkx
            TnJLUFdOYktvSFQvcm8yeUYrY2tNZTlzV0ZrCkczbU90QUZvNHM5MkFpRE8yYnV2
            aUY3SUphUkN6ZStQTG1aMDVnZ0Z2QU0KLS0tIE9GdVlkd3EzY0NwNWhQRVloRGZj
            VmJRQkpWZmFLT0dGNCszdU5KNmw1bWMKMyzZhuYKnL7uJ1gQNYEzWRCeTuhadYpn
            O2eNDXANYz1vT7BT9h3i8MGziOM2INlLu6U4Puh5TWk/Vb7f00CBWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    lastmodified: "2026-10-02T09:20:52Z"
    mac: ENC[AES256_GCM,data:aDWPFxlJI3raRGX+aQv6JMCvSHSJg4SKsUjHX0h4ZQil+HXDfXspJvWAGMN4RfYXNDaG5O5r+7ab+lJL4BFi9KEi2/B4V7HkhpG9VoFnBU8aKhSxtHyop+euyxpLfwQv/8dZ4JUN6Z3EnNX+LFARCEtjBCIzfu0qTjRUQOgN6P0=,iv:++nvKiz7ZxspWgytR9Y96I8bH3KgucoR3zfoHTT+E2g=,tag:l/qp+eYBtlnNj2vFbyCdTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
