apiVersion: ENC[AES256_GCM,data:p/w=,iv:suGmjx1ZXhUoY3RKHMnewaGmtl9nUeRlkXB9iD9ppXQ=,tag:Cu60bFg5doeUS05T4Vj31w==,type:str]
kind: ENC[AES256_GCM,data:T0pqsu/Q,iv:PcQ2NMBqxNnQOfpdZPmcTX363Mci/dPfHepOByIPBc4=,tag:+x98v3aZBXYGGO3DhdRReA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4tJtLhZp87R/yKnTlt1XYa9n,iv:UwCxpSVvWNuSo3oBIOYPVqVXk4Ewgh/QFiaNpRTwgfM=,tag:WQoQSQlCWrFW4IMvNcNzqA==,type:str]
    namespace: ENC[AES256_GCM,data:4TINPEsun5E=,iv:8hMo4ORKqnWBM4vcE3xDqi6x4YUH3lai94TM12uOHA0=,tag:T0vW/5FI6+b2W8DEmeZYdw==,type:str]
type: ENC[AES256_GCM,data:ObSxeykS,iv:ocae/dMePbhWGPWain4zGUBADB6RSOiE4jds2Vnjn54=,tag:/Mkg456xCkmc7pu1GcYwTg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:8NggaS0pAqM=,iv:zoOp8PfNrHWW1AbSBq9zd8/5GTm+1u4qO466PleRAy8=,tag:GRHTTiKrfbcUCOZuE8Gd3g==,type:str]
    password: ENC[AES256_GCM,data:dplqaNs+AwM2Ussl3sbRwpWHaXgV8wQ97EaFZhp4,iv:dg+zyCVBFUwCvLHNGZdIlgsVK6+iu9KpJebrmFxE4fQ=,tag:POzbL+iZC5/6uO0ypVtS2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSelpRYWllR1FvSDVkRVoz
            M1JYZ2x4ZHVwS3JZQ0dva2V4U2xqNEVtQlhNCkI0S1UzTkpwcXVwaGxlS0N1ZXBw
            WUhpUGJkc2VZbEdqcC85c29tZXhBSGMKLS0tIFBTRmNmUUV1c2lTNFRHbVQrWldG
            YkxGaDZzK0ZOT2R1bGtrTzZVOTVjbGcKUbeTl1HTclsOf7H4lK09jFrSpKVmZ9/b
            25uzI9o23CvdVt17Laqe4jCKlqry6xAB0nd/T187mfYM7Yg0OYCYIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    lastmodified: "2026-10-02T08:59:32Z"
    mac: ENC[AES256_GCM,data:3Ne4xDBaik79j6Ogz5PjXjelhvF66gvy93EipDZv4NCeYrPYfWGqzWoCAV+HnB1+xf3Mtxq2MfQtvuPBy/j4zujKh8aXzdy0xoiRNxDhXDc6riAeH0PWy2WctRF5gF/O0ZxM5oNldLISjabSejm3iTqQX/gPTNKbU9vONmwXVBA=,iv:NCcSKDvGz5WiKp7jvtVesefynenxEfQH1+teKS81064=,tag:vZB8vTDP0nj8A1ctcee4WQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
