apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stalwart-db
  namespace: stalwart
  labels:
    app.kubernetes.io/name: stalwart
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16-alpine
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
  bootstrap:
    initdb:
      database: stalwart
      owner: stalwart
      encoding: UTF8
      localeCType: C
      localeCollate: C
  enableSuperuserAccess: true
  managed:
    roles:
      - name: stalwart
        superuser: true
        login: true
