apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - admin-secret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - http-route.yaml
  - mail-service.yaml
