apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-config
  namespace: shelfmark
  labels:
    app.kubernetes.io/name: shelfmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn-single-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-books
  namespace: shelfmark
  labels:
    app.kubernetes.io/name: shelfmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-single-replica
