apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dispatcharr
  namespace: dispatcharr
spec:
  interval: 10m
  chart:
    spec:
      chart: dispatcharr
      version: "2.20.0"
      sourceRef:
        kind: HelmRepository
        name: dispatcharr
        namespace: dispatcharr
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          main:
            port: 9191
            targetPort: 9191

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DISPATCHARR_ENV: aio

    persistence:
      data:
        enabled: true
        size: 10Gi
        storageClass: longhorn-single-replica
      postgres-run:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 2Gi
