apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
  - namespace.yaml
  - pvc.yaml
  - config-pvc.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - bazarr.yaml
