apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-media
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-downloads
  namespace: arr-stack
  labels:
    app.kubernetes.io/name: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
