apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"penpot-credentials","namespace":"penpot"},"stringData":{"api-secret-key":"5dZwhCcKjhdQkNjGt8SUwYT8u4uNIYiR-cJbueHl8PoOhPPuxkSwMtTiYFIYzS3nXeo-l2m9mzyyJOjUy1B06Q","db-password":"7A0pxWpv41Nhd0MPCPjGSrdx4XTVeYywCB35s/yy/bM="},"type":"Opaque"}
  name: penpot-credentials
  namespace: penpot
stringData:
  api-secret-key: ENC[AES256_GCM,data:diGt4/2zpPoAqsRGXR6Zrcv3FpJ0hIlGT/9sn6UE/oaDBpZohYqtHQKhOIsww62tr8VPlw6KId/E3kr/709f0NyPjImY3LJTPLOf1y+lZ132VOL0fMI=,iv:ZqaCX1mW7uBdqdEPEHl3aOyym0iVPWemT3M6JQ2PysM=,tag:t7INwCVjFLuoSQB80PTFdw==,type:str]
  db-password: ENC[AES256_GCM,data:T2BrrYdvxAvVHxoJut4sKqIwMwnCtp5w4nltNdwyF8HjEYUdcDyDYM50qfo=,iv:vt3mHIRXEJNpX46oI6kvE87ecDST4/jhbX6FJ0rDa/8=,tag:Y7pYFYjaBW9cuaP9KbZhwQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRTNFY1QrODBLdzZhM1Ba
        QUozd0lhZk5TMVM0RW9EZDlxZ2swbGZERFhBCm1PbWVqd20wcTlxTWJiZGN6bmdh
        OFpXQnovTXB3RXBpRWd0M0pWQ2NzUE0KLS0tIHlhZFM4V1J4clBlMG0wd3U4aC9y
        MVVKYW9wRCtPUXZVVWkyTHk3Zm81bjAKDKX6BG0Lji4cjdRj+f0ntE1Ryylqku95
        sKgcS8WGGkk4NieW2x2R0J636wov3jT1dmLXQnQGZqVlUtOFlKqFMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T22:21:58Z"
  mac: ENC[AES256_GCM,data:+F57OLctu1S5XrrOoeBziqOSWtztIrRAHeLeL73RMKURC1b56w65HHRgfZ6v+rFK87ueguvGO5j2gaKr8BlCpAx6w3/v2IHiyrUe2GliMYB3SMunDzWC1fFqlBBAop1XQC8xYD8DW2BQkoQj3lRJmobrfXYFpZ7G1rWLUVBR41Q=,iv:rjr4farLGJXVVT60rn838Nd1xXk3m6BHJ2J4V7oWZv4=,tag:r34Ywdujyd2szzmfnnrd2g==,type:str]
  version: 3.13.1
