apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: penpot-db
  namespace: penpot
  labels:
    app.kubernetes.io/name: penpot
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  storage:
    size: 10Gi
    storageClass: longhorn-single-replica
  bootstrap:
    initdb:
      database: penpot
      owner: penpot
      secret:
        name: penpot-db-app
