apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - database.yaml
  - redis.yaml
  - credentials-secret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - http-route.yaml
