apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-assets
  namespace: penpot
  labels:
    app.kubernetes.io/name: penpot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-single-replica
