apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0
  storage:
    size: 10Gi
    storageClass: longhorn-single-replica
  bootstrap:
    initdb:
      database: immich
      owner: immich
      encoding: UTF8
      localeCType: C
      localeCollate: C
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  enableSuperuserAccess: true
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
