apiVersion: v1
data:
  password: ENC[AES256_GCM,data:l7hKxwd3h2O+fdhFXCbcLCkHar7LBdxXiZZrt+cTp+pod+wrwbxPfLfrXxFyLLhmI9j+g4G8Jebs0uy2,iv:eU6rLsrkQqqtLuItk1I+OQqAaU5jB3rCgF2TLaOmPhI=,tag:LV4ytfdbbDt7ZasfQVFI8Q==,type:str]
  username: ENC[AES256_GCM,data:02YWOd6V9Ok=,iv:Oxn6VY3XS4IznIjcfwsDVrCGMgmlxYeNpQ+u9q0hKds=,tag:k9ecPHKo4oIougKp5xuFSg==,type:str]
kind: Secret
metadata:
  name: immich-db-secret
  namespace: immich
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUFJCSGFVNURjVWdzWHg2
        M0cxcnJ2dE9PMThLZS9GMlB1U3UzQTNHQ2tVCmdTY0xMOFBzVGVDNzM4TDNRV3RT
        KzlFVXl4d3RkU0NMUmszVzRUU3hyL00KLS0tIEFjSkQySzUrY3NIclBMOXhnYmFR
        WFBFZ0lrWTZreEx1SGF2UVdOcklyWXMK9fGHrvxYg75wqUZg8/T7kFLdKW8IGNXm
        3NxQDtN8gvZ89GhWJE14NwkYCua0ey3dSfPEGaQWZfEAW+VxINyA3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T18:18:11Z"
  mac: ENC[AES256_GCM,data:DmSDVnyeenjm0MLFnuVw5MVZUeBr2OVo0Ljj4YxzsEACUIz2Jrs0gg86OVX0srj8PU8zm1ztazuThfnDU5Z/KEnpC6OgvICNoAh/Sbz2n0KTw8kj7lDJriq6QvWEM6YHhxJCvY/FStlo7RuJBVeHbKhIjF7MxUmvdO2tWu71sTc=,iv:605foKyFrjoPYM8KzHK9+XAU/JMOtelBNff1mxI4OHs=,tag:XZ6RnsNB25w4gaA9xMUjGA==,type:str]
  version: 3.13.1
