apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v1.118.0
            env:
              DB_HOSTNAME:
                value: immich-db-rw
              DB_USERNAME:
                value: immich
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-app
                    key: password
              DB_DATABASE_NAME:
                value: immich
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              IMMICH_MACHINE_LEARNING_URL: >
                {{ printf "http://%s-machine-learning:3003" .Release.Name }}
    immich:
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: docker.io/valkey/valkey
                tag: 9.1-alpine
                pullPolicy: IfNotPresent
      persistence:
        data:
          enabled: true
          size: 1Gi
          accessMode: ReadWriteOnce
          type: persistentVolumeClaim
  install:
    createNamespace: true
    timeout: 10m
  upgrade:
    timeout: 10m
