apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Kubernetes:
        - Grafana:
            icon: grafana.png
            href: http://grafana.simonbrundin.com
            siteMonitor: http://grafana.simonbrundin.com
            description: Dashboardarnas dashboard
        - pgAdmin:
            icon: pgadmin.png
            href: http://pgadmin.simonbrundin.com
            siteMonitor: http://pgadmin.simonbrundin.com
            description: Hantera Postgres-databaser
    - Egenutvecklat:
        - Plan:
            href: http://plan.simonbrundin.com
            siteMonitor: http://plan.simonbrundin.com
            description: Världens bästa planeringsapp 😎
    - Infra:
        - Unifi:
            href: https://unifi.ui.com/consoles/0CEA145690E500000000087652220000000008E9B7670000000067253CC5:1407354649/network/default/clients/main
            icon: unifi.png
            description: Min älskade gateway
    - Monitoring:
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.simonbrundin.com
            siteMonitor: https://uptime.simonbrundin.com
            description: Monitor homelab service uptime
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
