apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Kubernetes:
        - Grafana:
            icon: grafana.png
            href: http://grafana.simonbrundin.com
            description: Homepage is awesome
    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best
    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
    - Monitoring:
        - Uptime Kuma:
            href: https://uptime.simonbrundin.com
            description: Monitor homelab service uptime
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - uptimekuma:
        url: https://uptime.simonbrundin.com
        slug: plan
