apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: homepage
    repo: oci://ghcr.io/m0nsterrr/helm-charts
    version: 4.2.0
    releaseName: homepage
    namespace: homepage
    valuesFile: values.yaml
